import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Navbarlayout from "~/components/layouts/navbar/Navbarlayout";
import { Toaster } from "~/components/ui/toaster";
import Template from "./template";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <Navbarlayout />
          <Template>{children}</Template>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
